// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Character documents
 */
interface CharacterDocumentData {
  /**
   * Slug field in *Character*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: character.slug
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  slug: prismic.KeyTextField;

  /**
   * Image character field in *Character*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: character.image_character
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_character: prismic.ImageField<never>;

  /**
   * Name character field in *Character*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: character.name_character
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name_character: prismic.KeyTextField;

  /**
   * Description character field in *Character*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: character.description_character
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description_character: prismic.RichTextField;
}

/**
 * Character document from Prismic
 *
 * - **API ID**: `character`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CharacterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CharacterDocumentData>,
    "character",
    Lang
  >;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Subtitle hero field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.subtitle_hero
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle_hero: prismic.KeyTextField;

  /**
   * Title hero field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.title_hero
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_hero: prismic.KeyTextField;

  /**
   * Description hero field in *Home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.description_hero
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description_hero: prismic.RichTextField;

  /**
   * label button field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.label_button
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label_button: prismic.KeyTextField;

  /**
   * url button field in *Home*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home.url_button
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url_button: prismic.LinkField;

  /**
   * label trailer field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.label_trailer
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label_trailer: prismic.KeyTextField;

  /**
   * thumbnail trailer field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.thumbnail_trailer
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  thumbnail_trailer: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<HomeDocumentData>, "home", Lang>;

export type AllDocumentTypes = CharacterDocument | HomeDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      CharacterDocument,
      CharacterDocumentData,
      HomeDocument,
      HomeDocumentData,
      AllDocumentTypes,
    };
  }
}
